FROM node:12.2.0-alpine
LABEL version="1.0"
LABEL description="This is the dev version of the liblary app"
WORKDIR /app
COPY ["package.json","package-lock.json*","./"]
RUN npm install && npm cache clean --force
COPY . . 
EXPOSE 5000 
CMD ["npm","run","start:dev"]